jwt_key = "pass"
KEYS = ['POSTGRES_USER', 'POSTGRES_PASSWORD',
        'POSTGRES_HOSTNAME', 'POSTGRES_DB']
# USER, PASSWORD, HOSTNAME, DATABASE = (env.get(i, 'test') for i in KEYS)
# SQLALCHEMY_DATABASE_URL = f'postgresql://{USER}:{PASSWORD}@{HOSTNAME}/{DATABASE}'
SQLALCHEMY_DATABASE_URL = "sqlite:///db.sqlite"
USERS_TABLENAME = "users_db"
STUDENTS_TABLENAME = "students_db"
ADMINS_TABLENAME = "admins_db"
WORKERS_TABLENAME = "wokers_db"